# Generated by Django 4.1.7 on 2023-03-01 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paint_status', models.CharField(choices=[('P', 'Primed'), ('D', 'Detailed'), ('C', 'Completed')], default='P', max_length=1)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.model')),
            ],
        ),
    ]
