# Generated by Django 4.1.7 on 2023-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_painting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='paint_status',
            new_name='painting_status',
        ),
        migrations.AlterField(
            model_name='painting',
            name='date',
            field=models.DateField(verbose_name='Painted Date'),
        ),
    ]
