# Generated by Django 4.1.7 on 2023-03-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_paint'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='paints',
            field=models.ManyToManyField(to='main_app.paint'),
        ),
    ]
